#!/bin/bash -x

set -e

if [ "${RSA_KEYFILE}" ]
  then
  cp ${RSA_KEYFILE} /root/
  openconnect -u ${VPN_USERNAME} --script-tun --script "ocproxy -D 2280 -k 60 -g" --token-mode=rsa --no-cert-check ${VPN_GATEWAY}
  exit 1
fi

if [ "${AUTHGROUP}" ]
  then
  echo ${PASSWORD} | openconnect -u ${VPN_USERNAME} --script-tun --script "ocproxy -D 2280 -k 60 -g" --authgroup=${AUTHGROUP} --no-cert-check ${VPN_GATEWAY} --passwd-on-stdin
  exit 1
fi
