#!/bin/bash -x
set -e

VPN_GATEWAY=${VPN_GATEWAY}
VPN_USERNAME=${VPN_USERNAME}
RSA_KEYFILE=${RSA_KEYFILE}
TUNNEL_INTERFACE=${TUNNEL_INTERFACE}
NODE_INTERFACE=${NODE_INTERFACE}
NETWORKS=${NETWORKS}
DEFAULT_GATEWAY=$(ip route show default | awk '/default/ {print $3}'|uniq)

function reconfigure_routes() {
if [ "$NETWORKS" ]
then
ip route del 0.0.0.0/0 via 0.0.0.0 dev $TUNNEL_INTERFACE
# Add default route for non-vpn traffic
ip route add 0/0 via $DEFAULT_GATEWAY dev $NODE_INTERFACE
# Add static routes for data center networks via tunnel interface
for network in ${NETWORKS[@]}
do
    ip route add $network dev $TUNNEL_INTERFACE
done
fi
}

if [ "$RSA_KEYFILE" ]
then
cp ${RSA_KEYFILE} /root/
fi

openconnect -b -u $VPN_USERNAME -s /usr/share/vpnc-scripts/vpnc-script --token-mode=rsa --no-cert-check $VPN_GATEWAY
failed=`echo $?`
if [ -n $failed ]
then
    reconfigure_routes
fi
